Update build-padavan.yml

diff --git a/.github/workflows/build-padavan.yml b/.github/workflows/build-padavan.yml
--- a/.github/workflows/build-padavan.yml
+++ b/.github/workflows/build-padavan.yml
@@ -39,12 +39,19 @@ jobs:
       env:
         TNAME: hanwckf_k2
       run: |
+        if [ -f public/$TNAME.config ] ; then
+        mv -f public/$TNAME.config /opt/rt-n56u/trunk/configs/templates/$TNAME.config
+        echo "config file copy success"
+        else
+        echo "public/$TNAME.config not found"
+        exit 2
+        fi
         cd /opt/rt-n56u/trunk
-        if [ ! -f public/$TNAME.config ] ; then
-        echo "public/$TNAME.config not found "
+        if [ ! -f configs/templates/$TNAME.config ] ; then
+        echo "configs/templates/$TNAME.config not found "
         exit 1
         fi
-        cp -f public/$TNAME.config .config
+        cp -f configs/templates/$TNAME.config .config
         sudo ./clear_tree
         sudo ./build_firmware_modify $TNAME 0
         sudo mv -f images/*.trx /opt/images/
